# Generated by Django 5.2.1 on 2025-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_remove_customuser_salary_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('China', 'China'), ('Japan', 'Japan'), ('India', 'India'), ('Israel', 'Israel'), ('Russia', 'Russia'), ('USA', 'USA'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
